# Generated by Django 5.2.4 on 2025-07-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_alter_comment_club_alter_prediction_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='selected_club',
            new_name='active_club',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supported_clubs',
            field=models.ManyToManyField(related_name='profiles', to='engagement.club'),
        ),
    ]
