# Generated by Django 5.2.4 on 2025-07-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0008_newscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
