# Generated by Django 5.2.4 on 2025-07-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0009_newscomment_dislikes_newscomment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
