# Generated by Django 5.2.4 on 2025-08-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0014_prediction_verified_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FixtureResult',
        ),
    ]
