# Generated by Django 5.2.4 on 2025-08-12 21:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0015_delete_fixtureresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default='14:00')),
                ('is_live', models.BooleanField(default=False)),
                ('final_result', models.CharField(blank=True, max_length=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagement.club')),
            ],
        ),
    ]
