# Generated by Django 5.2.4 on 2025-08-20 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0017_alter_prediction_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], default='Neutral', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='engagement.fixture')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagement.userprofile')),
            ],
        ),
    ]
