# Generated by Django 5.2.4 on 2025-08-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0018_matchcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('votes_option1', models.IntegerField(default=0)),
                ('votes_option2', models.IntegerField(default=0)),
                ('votes_option3', models.IntegerField(blank=True, default=0, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagement.poll')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagement.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'poll')},
            },
        ),
    ]
